services:
  - type: web
    name: jsons-and-dragons
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/jsons-and-dragons/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html